FROM alpine AS builder

# Download QEMU, see https://github.com/docker/hub-feedback/issues/1261
ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1

FROM alpine:3

# Add QEMU
COPY --from=builder qemu-arm-static /usr/bin

RUN apk add -U --no-cache curl httpie sudo
RUN echo  '%wheel ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/wheel && \
adduser -u 1000 user -D && \
addgroup user wheel

# chisel: a single static Go binary (reverse tunnel client/server). Same mechanism as the main
# Dockerfile (TARGETARCH+TARGETVARIANT -> chisel arch), but preset to this file's architecture (arm/v7 = armv7)
ARG TARGETARCH=arm
ARG TARGETVARIANT=v7
ARG CHISEL_VERSION=1.11.5
RUN curl -fsSL "https://github.com/jpillora/chisel/releases/download/v${CHISEL_VERSION}/chisel_${CHISEL_VERSION}_linux_${TARGETARCH}${TARGETVARIANT}.gz" \
      | gunzip > /usr/local/bin/chisel \
 && chmod +x /usr/local/bin/chisel \
 && [ -s /usr/local/bin/chisel ]

USER 1000
WORKDIR /home/user
